web:
  image: debian:jessie
  volumes:
    - .:/var/www
drupal:
  build: docker/drupal
  links:
    - db
    - selenium
  ports:
    - 80
  volumes_from:
    - web
db:
  image: mariadb
  environment:
    MYSQL_USER: drupal
    MYSQL_PASSWORD: drupal
    MYSQL_DATABASE: drupal
    MYSQL_ROOT_PASSWORD: root
selenium:
  image: selenium/standalone-firefox
  ports:
    - 4444
